GET http://localhost:3000/api/members

###
GET http://localhost:3000/api/members?team=Engineering

###
GET http://localhost:3000/api/members/3

###
POST http://localhost:3000/api/members
Content-Type: application/json

{
   
    "name": "Mike",
    "team": "Sales"
}

###
PUT http://localhost:3000/api/members/7
Content-Type: application/json

{
    "id": 1,
    "name": "Tom",
    "team": "Marketing"
}

###
DELETE http://localhost:3000/api/members/5